#!/bin/bash
# cryptool regression test script, verifies that cryptool will work on your
# platform. Note, does not test HSM functions.
# Command line arg -v or -vv enables cryptool verbosity

set -e
set -v
set -u

dir=regress.tempdir
mkdir -p $dir
cd $dir
cryptool="../cryptool $*"
TMPDIR=$PWD

head -c1048576 /dev/urandom > data

# Generating master key
rm -f master.[sp]
$cryptool generate -d 1 -i "this is the master" master
$cryptool dump master.p
$cryptool dump master.s
b=$($cryptool dump -b master.p); echo $b; ((b==4096))
b=$($cryptool dump -b master.s); echo $b; ((b==4096))
mp=$($cryptool dump -m master.p); echo $mp
ms=$($cryptool dump -m master.s); echo $ms; [[ $ms == $mp ]]
np=$($cryptool dump -c master.p); echo $np
ns=$($cryptool dump -c master.s); echo $ns; [[ $ns == $np* ]]

# Generating slave key
rm -f slave.[sp]
$cryptool generate -b 2048 -c "chacha" -i "this is the slave" slave master
$cryptool check slave master
$cryptool dump slave.p
$cryptool dump slave.s
b=$($cryptool dump -b slave.p); echo $b; ((b==2048))
b=$($cryptool dump -b slave.s); echo $b; ((b==2048))
mp=$($cryptool dump -m slave.p); echo $mp
ms=$($cryptool dump -m slave.s); echo $ms; [[ $ms == $mp ]]
np=$($cryptool dump -c slave.p); echo $np
ns=$($cryptool dump -c slave.s); echo $ns; [[ $ns == $np* ]]

# Creating locked key
# ENTER "zzzz" AT THE PROMPTS! 
$cryptool lock master.s > locked.s

# Testing sign/verify
$cryptool sign master < data > signed
$cryptool info < signed
$cryptool verify master < signed > verified
diff -q data verified

# Testing sign/verify with locked key
$cryptool sign master.p locked.s < data > signed
$cryptool info < signed
$cryptool verify master < signed > verified
diff -q data verified

# Testing sign/verify with slave key
$cryptool sign slave < data > signed 
$cryptool info < signed
$cryptool verify slave master < signed > verified
diff -q data verified

# Testing encrypt/decrypt
$cryptool encrypt master < data > enc
$cryptool info < enc
$cryptool decrypt master < enc > dec
diff -q data dec

# Testing decrypt with locked key
$cryptool decrypt locked < enc > dec 
diff -q data dec

# Testing detached sign/verify
# If this fails it may mean your openssl doesn't properly support sha256
$cryptool sign -d master < data > detached
$cryptool verify -d detached master < data

# Testing detached sign/verify with locked key
$cryptool sign -d locked < data > detached
$cryptool verify -d detached master < data

# Delete only the files we just created so we can detect bogus files 
rm data dec detached enc locked.s master.p master.s signed slave.p slave.s verified
cd ..
rmdir $dir
# Success!
